//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioMusicaWCF
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Conciertos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conciertos()
        {
            this.DetallesConcierto = new HashSet<DetallesConcierto>();
        }
    
        public int Id { get; set; }
        public int IdArtista { get; set; }
        public string Lugar { get; set; }
        public System.DateTime Fecha { get; set; }

        [Newtonsoft.Json.JsonIgnore]
        public virtual Artistas Artistas { get; set; }

        [Newtonsoft.Json.JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesConcierto> DetallesConcierto { get; set; }
    }
}
