//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioMusicaWCF
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class DetallesConcierto
    {
        public int IdConcierto { get; set; }
        public int IdCancion { get; set; }
        public int Orden { get; set; }
    
        [Newtonsoft.Json.JsonIgnore]
        public virtual Canciones Canciones { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual Conciertos Conciertos { get; set; }
    }
}
